#
language: java
jdk: oraclejdk11
dist: trusty
branches:
  only:
    - develop
install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
script:
  - mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -P${TRAVIS_BRANCH} -Poptions clean install deploy
